version: '2'
services:
  # client:
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   build: ./front
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend
  backend:
    build: ./api
    ports:
      - '9003:9003'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  
