export default {
	CC: 'coordinating conjunction',
	CD: 'cardinal digit',
	DT: 'determiner',
	EX: 'existential there (like: “there is” … think of it like “there exists”)',
	FW: 'foreign word',
	IN: 'preposition/subordinating conjunction',
	JJ: 'adjective',
	JJR: 'adjective, comparative',
	JJS: 'adjective, superlative',
	LS: 'list marker',
	MD: 'modal',
	NN: 'noun, singular',
	NNS: 'noun plural',
	NNP: 'proper noun, singular',
	NNPS: 'proper noun, plural',
	PDT: 'predeterminer',
	POS: 'possessive ending parent’s',
	PRP: 'personal pronoun',
	PRP$: 'possessive pronoun',
	RB: 'adverb',
	RBR: 'adverb, comparative',
	RBS: 'adverb, superlative',
	RP: 'particle give up',
	TO: 'to go ‘to’ the store.',
	UH: 'interjection',
	VB: 'verb, base form take',
	VBD: 'verb, past tense, took',
	VBG: 'verb, gerund/present participle taking',
	VBN: 'verb, past participle is taken',
	VBP: 'verb, sing. present, known-3d take',
	VBZ: 'verb, 3rd person sing. present takes',
	WDT: 'wh-determiner which',
	WP: 'wh-pronoun who, what',
	WP$: 'possessive wh-pronoun whose',
	WRB: 'wh-adverb where, when',
};
